# Нашли баг/Есть идея по улучшению? пишите в обсуждение ресурса или в дискорд _encourager_
# Права:
# greatcombat.teleports.bypass - право на обход запрета телепортации
# greatcombat.powerups.bypass - право на обход отключения поверапов
# greatcombat.commands.bypass - право на обход блокировки команд
# greatcombat.cooldowns.bypass - право на обход задержек на предметы
# greatcombat.kill.bypass - право на обход убийства при выходе и кике

#Отправка анонимной статистики
metrics: true
#Будут ли заполняться плейсхолдеры в сообщениях и скорборде
use-papi: true
# Настройки отображения времени
time:
  seconds:
    form1: 'секунду'
    form3: 'секунды'
    form5: 'секунд'
  minutes:
    form1: 'минуту'
    form3: 'минуты'
    form5: 'минут'
  hours:
    form1: 'час'
    form3: 'часа'
    form5: 'часов'
# Какой плагин будет использоваться для отключения поверапов
# На данный момент доступны CMI Essentials и Vanilla
# Если вам нужна поддержка других плагинов - пишите
server-manager: Essentials
# Сейчас доступен только TAB, возможно добавлю ванильный
# Если нужны другие менеджеры - пишите
#scoreboard-manager: TAB
# Длительность режима пвп в секундах
pvp-time: 30
# Задержки на предметы в формате MATERIAL: перевод;время;обработчики
# Доступные обработчики:
# CONSUME - когда вы съедаете выпиваете предмет
# RIGHT_CLICK_AIR - пкм по воздуъу
# RIGHT_CLICK_BLOCK - пкм по блоку
# LEFT_CLICK_AIR - лкм по воздуху
# LEFT_CLICK_BLOCK - пкм по блоку
# Записывайте обработчики через запятую CONSUME,RIGHT_CLICK_AIR и т.д
items-cooldowns:
  GOLDEN_APPLE: 'Золотое яблоко;10;CONSUME'
  ENCHANTED_GOLDEN_APPLE: 'Зачарованное золотое яблоко;30;CONSUME'
  ENDER_PEARL: 'Эндер-жемчуг;10;RIGHT_CLICK_AIR,RIGHT_CLICK_BLOCK'
# Разрешить ли телепортации во время пвп?
# Будет работать только если ServerManager не Vanilla
allow-teleport: false
# Миры в которых не будет начинаться пвп режим
ignored-worlds: []
# Бой не будет начинаться если у игрока есть поверапы из этого списка
# Список поверапов
# GAMEMODE - любой режим кроме выживания
# VANISH - включенный ваниш
# FLY - включенный флай
# GOD - включенный год
# WALKSPEED - увеличенная скорость ходьбы
prevent-start-if-damager:
  - GAMEMODE
  - VANISH
# Бой не будет начинаться если у атакуемого есть эти поверапы
prevent-start-if-target:
  - GAMEMODE
  - VANISH
  - GOD
# какие поверапы будут отключаться для атакующего
disable-for-damager:
  - GOD
  - GAMEMODE
  - FLY
  - VANISH
# Какие поверапы будут отключаться для атакуемого
disable-for-target:
  - WALKSPEED
  - FLY
# Убивать игроков при выходе с сервера во время пвп
kill-on-leave: true
# Убивать игроков которых кикнули во время пвп
kill-on-kick: true
# Список причин по которым игрока нужно убить
# Если список пуст будет убивать постоянно
kick-messages: []
commands:
  # Если WHITELIST, будут доступны все команды из списка
  # Если BLACKLIST будут доступны все команды кроме списка
  type: WHITELIST
  # Менять табкомплит с учётом забаненых команд
  change-tabcomplete: true
  #Если команды пустые будут доступны все
  commands:
    - tell
    - msg
    - check
