# Нашли баг/Есть идея по улучшению? пишите в обсуждение ресурса или в дискорд _encourager_
# Права:
# greatcombat.teleports.bypass - право на обход запрета телепортации
# greatcombat.powerups.bypass - право на обход отключения поверапов
# greatcombat.commands.bypass - право на обход блокировки команд
# greatcombat.cooldowns.bypass - право на обход задержек на предметы
# greatcombat.kill.bypass - право на обход убийства при выходе и кике

#Отправка анонимной статистики
metrics: true
#Уведомления о наличии обновлений
update-checker: true
#Будут ли заполняться плейсхолдеры в сообщениях и скорборде
use-papi: true
# Настройки отображения времени
time:
  seconds:
    form1: 'секунду'
    form3: 'секунды'
    form5: 'секунд'
  minutes:
    form1: 'минуту'
    form3: 'минуты'
    form5: 'минут'
  hours:
    form1: 'час'
    form3: 'часа'
    form5: 'часов'
# Какой плагин будет использоваться для отключения поверапов
# На данный момент доступны CMI Essentials и Vanilla
# Если вам нужна поддержка других плагинов - пишите
server-manager: Essentials
# Доступны TAB и FastBoard
# FastBoard не требует сторонних плагинов
scoreboard-manager: FastBoard
# Длительность режима пвп в секундах
pvp-time: 30
# Период между тиком игрока (Как часто будет обновляться скорборд боссбар и проверяться не истекло ли время)
# При уменьшении может быть большая нагрузка, особенно если используются плагины обрабатывающие tickevent
tick-interval: 20
# Если оставшееся время будет меньше чем это число бой остановится (в миллисекундах)
# Измените если возникают проблемы с отрицательным прогрессом боссбара
time-to-stop: 1
# От каких снарядов не будет даваться пвп
ignored-projectile:
  - EGG
  - SNOWBALL
# Задержки на предметы в формате MATERIAL: перевод;время;обработчики
# Доступные обработчики:
# CONSUME - когда вы съедаете выпиваете предмет
# RIGHT_CLICK_AIR - пкм по воздуъу
# RIGHT_CLICK_BLOCK - пкм по блоку
# LEFT_CLICK_AIR - лкм по воздуху
# LEFT_CLICK_BLOCK - пкм по блоку
# BLOCK_BREAK - поломка блока
# RESURRECT_OFFHAND - при перерождении на предмет во второй руке
# RESURRECT_MAINHAND - при перерождении на предмет в главной руке
# Если предмет с RESURRECT обработчиком в кд игрок не воскреснет
# Записывайте обработчики через запятую CONSUME,RIGHT_CLICK_AIR и т.д
items-cooldowns:
  TOTEM_OF_UNDYING: 'Тотем;60;RESURRECT_OFFHAND,RESURRECT_MAINHAND'
  GOLDEN_APPLE: 'Золотое яблоко;10;CONSUME'
  ENCHANTED_GOLDEN_APPLE: 'Зачарованное золотое яблоко;30;CONSUME'
  ENDER_PEARL: 'Эндер-жемчуг;10;RIGHT_CLICK_AIR,RIGHT_CLICK_BLOCK'
#Предметы взаимодействие с которыми в пвп будет запрещено
#Записывать в формате перевод;тип предмета;обработчики
#обработчики такие же как и в кулдаунах
#типы предметов
#INTERACTED_ITEM - предмет в руке с которым взаимодействуют
#INTERACTED_BLOCK - блок с которым взаимодействует игрок
# Если предмет с обработчиком RESURRECT находится в указаной руке игрок не воскреснет
preventable-items:
  DIAMOND_ORE: Алмазный регион;INTERACTED_ITEM;RIGHT_CLICK_AIR,RIGHT_CLICK_BLOCK
  FIREWORK_ROCKET: Фейерверк;INTERACTED_ITEM;RIGHT_CLICK_AIR,RIGHT_CLICK_BLOCK
  ENDER_CHEST: Эндерсундук;INTERACTED_ITEM,INTERACTED_BLOCK;RIGHT_CLICK_AIR,RIGHT_CLICK_BLOCK
# Разрешить ли телепортации во время пвп?
# Будет работать только если ServerManager не Vanilla
allow-teleport: false
# Миры в которых не будет начинаться пвп режим
ignored-worlds: []
# Бой не будет начинаться если у игрока есть поверапы из этого списка
# Список поверапов
# GAMEMODE - любой режим кроме выживания
# VANISH - включенный ваниш
# FLY - включенный флай
# GOD - включенный год
# WALKSPEED - увеличенная скорость ходьбы
prevent-start-if-damager:
  - GAMEMODE
  - VANISH
# Бой не будет начинаться если у атакуемого есть эти поверапы
prevent-start-if-target:
  - GAMEMODE
  - VANISH
  - GOD
# какие поверапы будут отключаться для атакующего
disable-for-damager:
  - GOD
  - GAMEMODE
  - FLY
  - VANISH
# Какие поверапы будут отключаться для атакуемого
disable-for-target:
  - WALKSPEED
  - FLY
# Убивать игроков при выходе с сервера во время пвп
kill-on-leave: true
# Убивать игроков которых кикнули во время пвп
kill-on-kick: true
# Список причин по которым игрока нужно убить
# Если список пуст будет убивать постоянно
kick-messages: []
commands:
  # Если WHITELIST, будут доступны все команды из списка
  # Если BLACKLIST будут доступны все команды кроме списка
  type: WHITELIST
  # Менять табкомплит с учётом забаненых команд
  change-tabcomplete: true
  #Если команды пустые будут доступны все
  commands:
    - tell
    - msg
    - check

