# Find bug/Any ideas for improvement? Write me in discord _encourager_
# Plugin permissions:
# greatcombat.teleports.bypass - teleports bypass permission
# greatcombat.powerups.bypass - powerups disable bypass permission
# greatcombat.commands.bypass - commands send bypass permission
# greatcombat.cooldowns.bypass - items cooldowns bypass permission
# greatcombat.kill.bypass - kill on quit and kick bypass permission

# LEGACY - &#RRGGBB
# MINIMESSAGE - <color>
colorizer: LEGACY
#Send anonymous statistic
metrics: true
#Notify updates of plugin in console
update-checker: true
#Will placeholders be filled in scoreboards and messages
#In messages, placeholders are filled in for the player who receives them
use-papi: true
# Time displaying
time:
  seconds:
    form1: 'second'
    form3: 'seconds'
    form5: 'seconds'
  minutes:
    form1: 'minute'
    form3: 'minutes'
    form5: 'minutes'
  hours:
    form1: 'hour'
    form3: 'hours'
    form5: 'hours'
# Plugin which will be used to disable powerups
# Available CMI Essentials and Vanilla
# If you need integrate to other plugins - write me
server-manager: Essentials
# Available TAB и FastBoard
# FastBoard don't require other plugins
scoreboard-manager: FastBoard
# Combat duration in seconds
pvp-time: 30
# Player tick delay (How often will scoreboard and bossbar update)
# Small value may produse a lags if you have plugins that handle tickevent
tick-interval: 20
# If remaining time is smaller that this value combat is stop (in ms)
# Change if you have a problems with negative bossbar progress
time-to-stop: 1
# Projectiles that couldn't start combat
ignored-projectile:
  - EGG
  - SNOWBALL
# Available handlers:
# CONSUME - while you eat item
# RIGHT_CLICK_AIR - right click air
# RIGHT_CLICK_BLOCK - right click block
# LEFT_CLICK_AIR - left click air
# LEFT_CLICK_BLOCK - right click block
# BLOCK_BREAK - while you break block
# RESURRECT_MAINHAND - while player resurrect with item in main hand
# RESURRECT_OFFHAND - while player resurrect with item in off hand
items-cooldowns:
  #Название может быть любым
  CHORUS_FRUIT:
    translation: 'Хорус'
    handlers:
      - CONSUME
    #Чтобы получить предмет в виде base64 возьмите его в руку и пропишите /combat copy
    base64: 'H4sIAAAAAAAA/+NiYGBm4HZJLEkMSy0qzszPY2DgkuJgYMpMYRDLzcxLTS5KTCuxSs7ILyotjk8rKs0sYWRgdc4vzQPSAGpDd/c8AAAA'
    time: 20
    #Для ванильных предметов рекомендую ставить true т.к проверка обходится банальным переименованием предмета
    set-material-cooldown: true
  GOLDEN_APPLE:
    translation: 'Золотое яблоко'
    handlers:
      - CONSUME
    base64: 'H4sIAAAAAAAA/+NiYGBm4HZJLEkMSy0qzszPY2DgkuJgYMpMYRDLzcxLTS5KTCuxSs/PSUnNi08sKMhJZWRgdc4vzSthZAAAKVnRWDwAAAA='
    time: 30
    set-material-cooldown: true
#Items interact with that will be blocked in combat
#handlers is similar with cooldowns
#prevention item types:
#INTERACTED_ITEM - item in hand
#INTERACTED_BLOCK - block that was interacted
# If RESURRECT player will die
preventable-items:
  DIAMOND_ORE:
    translation: 'регион'
    handlers:
      - RIGHT_CLICK_BLOCK
      - RIGHT_CLICK_AIR
    types:
      - INTERACTED_ITEM
    #Чтобы получить предмет в виде base64 возьмите его в руку и пропишите /combat copy
    base64: 'H4sIAAAAAAAA/+NiYGBm4HZJLEkMSy0qzszPY2DgkuJgYMpMYRDNzcxLTS5KTCuxSslMzM3PS4nPL0plZGB1zi/NK2FkAADqMtJCOwAAAA=='
# Will work only if ServerManager not Vanilla
allow-teleport: false
# Worlds where combat couldn't start
ignored-worlds: []
# Combat couldn't start if player has this powerups
# Available powerups
# GAMEMODE - any gamemode except survival
# VANISH - enabled vanish
# FLY - enabled fly
# GOD - enabled god
# WALKSPEED - increased walking speed
prevent-start-if-damager:
  - GAMEMODE
  - VANISH
# Combat couldn't start if target player has this powerups
prevent-start-if-target:
  - GAMEMODE
  - VANISH
  - GOD
# Wich powerups will be disabled for damager
disable-for-damager:
  - GOD
  - GAMEMODE
  - FLY
  - VANISH
# Wich powerups will be disabled for target
disable-for-target:
  - WALKSPEED
  - FLY
# Should plugin kill a player if he quit server during combat
kill-on-leave: true
# Should plugin kill a player if he was kicked during combat
kill-on-kick: true
# List of reasons will be player killed
# If its empty player always will be killed
kick-messages: []
commands:
  # If the type is WHITELIST, all the commands from the list will be available to the player
  # If the BLACKLIST type is used, all commands except those in the list will be available to the player.
  type: WHITELIST
  # Should plugin change the tabcomplete to the available commands?
  change-tabcomplete: true
  #If empty all commands will be available
  commands:
    - tell
    - msg
    - check

