name: GreatCombat
version: '${project.version}'
main: dev.enco.greatcombat.GreatCombat
api-version: '1.16'
softdepend:
  - CMI
  - Essentials
  - PlaceholderAPI
depend:
  - TAB
libraries:
  - com.github.ben-manes.caffeine:caffeine:3.1.8
